# Generated by Django 5.0.6 on 2024-06-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_user_id_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='user_id',
        ),
    ]
